#!/usr/bin/env node
//! Launches a throwaway agent for the end-to-end suite.
//
// The agent is *not* built here. The UI is embedded into the binary by
// `include_dir!` at compile time, so a build started from this script would
// race the very thing it is meant to serve. Building is the developer's (or
// CI's) job, in this order, and this script only checks the result exists:
//
//     cd ui && trunk build
//     cargo build -p automate
//
// Everything the agent writes — the database, the encryption key beside it, the
// configuration itself — goes into a fresh temporary directory that is removed
// when the process exits, so a run never sees another run's records and never
// touches the developer's own `config.toml` or `database.sqlite`.

import { spawn } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(here, "..", "..");

const PORT = Number(process.env.AUTOMATE_E2E_PORT ?? 8099);

/**
 * The agent binary to run.
 *
 * `AUTOMATE_E2E_BINARY` wins outright when it is set, and is an error when it
 * names something that is not there — falling back to a different binary than
 * the one that was explicitly asked for would test the wrong thing and say
 * nothing about it.
 *
 * Otherwise both profiles are accepted, because either is a perfectly good
 * thing to test against and a developer who has just run `cargo build
 * --release` should not be told to build again. When both exist the newer one
 * wins, on the assumption that it is the one just built.
 */
function resolveBinary() {
  const suffix = process.platform === "win32" ? ".exe" : "";

  const override = process.env.AUTOMATE_E2E_BINARY;
  if (override) {
    if (!fs.existsSync(override)) {
      throw new Error(
        `AUTOMATE_E2E_BINARY points at ${override}, which does not exist.`,
      );
    }
    return override;
  }

  const candidates = [
    path.join(repoRoot, "target", "debug", `automate${suffix}`),
    path.join(repoRoot, "target", "release", `automate${suffix}`),
  ];

  const found = candidates
    .filter((candidate) => fs.existsSync(candidate))
    .map((candidate) => ({ candidate, mtime: fs.statSync(candidate).mtimeMs }))
    .sort((a, b) => b.mtime - a.mtime);

  if (found.length === 0) {
    throw new Error(
      [
        "",
        "No `automate` binary was found, so there is nothing to test against.",
        "",
        "The UI is embedded into the binary at compile time, so it has to be",
        "built first — building the agent against an empty `ui/dist` produces an",
        "agent that answers `GET /` with a 500. Build both, in this order:",
        "",
        "    cd ui && trunk build",
        "    cargo build -p automate",
        "",
        `Looked in:\n${candidates.map((c) => `    ${c}`).join("\n")}`,
        "",
      ].join("\n"),
    );
  }

  return found[0].candidate;
}

/**
 * Removes scratch directories a previous run did not get to.
 *
 * The cleanup below handles every ordinary exit, but a run that was SIGKILLed —
 * a cancelled CI job, a crash — leaves its directory (and the database
 * encryption key inside it) behind. Only directories old enough that no live
 * run could own them are touched.
 */
function sweepStaleWorkspaces() {
  const cutoff = Date.now() - 6 * 60 * 60 * 1000;

  let entries;
  try {
    entries = fs.readdirSync(os.tmpdir());
  } catch {
    return;
  }

  for (const entry of entries) {
    if (!entry.startsWith("automate-e2e-")) {
      continue;
    }

    const stale = path.join(os.tmpdir(), entry);
    try {
      if (fs.statSync(stale).mtimeMs < cutoff) {
        fs.rmSync(stale, { recursive: true, force: true });
      }
    } catch {
      // Another run may own it, or it may have just gone. Either way it is not
      // this run's problem.
    }
  }
}

/**
 * A fresh directory holding this run's configuration and database.
 *
 * The database's encryption key is written to `<database>.key`, so the whole
 * lot has to live somewhere disposable or a run would leave a key behind in the
 * repository.
 */
function prepareWorkspace() {
  const directory = fs.mkdtempSync(path.join(os.tmpdir(), "automate-e2e-"));
  const configPath = path.join(directory, "config.toml");
  const databasePath = path.join(directory, "database.sqlite");

  // `user_acl` and `admin_acl` of `true` admit everybody, which is what makes
  // the UI usable with no identity provider and no sign-in step. The suite is
  // testing the admin UI, not the authentication in front of it.
  fs.writeFileSync(
    configPath,
    [
      "# Generated by e2e/scripts/start-agent.mjs. Do not edit; it is thrown away.",
      "[web]",
      `address = "127.0.0.1:${PORT}"`,
      `database = ${JSON.stringify(databasePath)}`,
      "",
      "[web.auth]",
      "user_acl  = 'true'",
      "admin_acl = 'true'",
      "",
    ].join("\n"),
    "utf8",
  );

  return { directory, configPath };
}

const binary = resolveBinary();
sweepStaleWorkspaces();
const { directory, configPath } = prepareWorkspace();

console.log(`[e2e] agent binary:  ${binary}`);
console.log(`[e2e] workspace:     ${directory}`);
console.log(`[e2e] listening on:  http://127.0.0.1:${PORT}`);

// `--env` is not optional here, and it must point at a path that does not
// exist. The agent calls `dotenvy::from_path_override` on whatever it is given,
// defaulting to `.env`; this repository's root `.env` is a *named pipe*, and
// `Path::exists()` says a FIFO exists, so an agent started from the repository
// root blocks forever inside that read with nothing on stdout to say why. A
// path in the scratch directory cannot be a pipe somebody left lying around.
const child = spawn(
  binary,
  ["--config", configPath, "--env", path.join(directory, ".env.absent")],
  {
    // Also run from the scratch directory, so nothing the agent resolves
    // relatively can reach the repository's own `.env`, `config.toml` or
    // `database.sqlite`.
    cwd: directory,
    stdio: ["ignore", "inherit", "inherit"],
    env: process.env,
  },
);

let cleanedUp = false;

function cleanUp() {
  if (cleanedUp) {
    return;
  }
  cleanedUp = true;

  if (child.exitCode === null && child.signalCode === null) {
    child.kill("SIGTERM");
  }

  try {
    fs.rmSync(directory, { recursive: true, force: true });
  } catch (error) {
    console.error(`[e2e] could not remove ${directory}: ${error}`);
  }
}

process.on("exit", cleanUp);
for (const signal of ["SIGINT", "SIGTERM", "SIGHUP"]) {
  process.on(signal, () => {
    cleanUp();
    process.exit(130);
  });
}

child.on("error", (error) => {
  console.error(`[e2e] failed to start the agent: ${error.message}`);
  cleanUp();
  process.exit(1);
});

child.on("exit", (code, signal) => {
  cleanUp();
  process.exit(code ?? (signal ? 143 : 1));
});
