use std::sync::Arc;

use chrono::Utc;
use jsonwebtoken::{Algorithm, EncodingKey, Header};

use crate::config::GitHubAppConfig;
use crate::prelude::*;

const GITHUB_API_URL: &str = "https://api.github.com";

/// Installation tokens live for an hour. Caching them for slightly less leaves
/// enough margin that a long-running job cannot be caught out mid-flight.
const TOKEN_CACHE_MINUTES: i64 = 50;

/// GitHub rejects app JWTs whose expiry is more than ten minutes away, and
/// backdates `iat` slightly to tolerate clock skew between us and GitHub.
const JWT_TTL_SECONDS: i64 = 9 * 60;
const JWT_SKEW_SECONDS: i64 = 60;

const TOKEN_CACHE_PARTITION: &str = "github/installation-token";

/// An account which has installed the GitHub App.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct GitHubInstallation {
    pub id: u64,
    /// The user or organization the App is installed on.
    pub account: String,
    /// `User` or `Organization`.
    pub account_type: String,
}

/// Authenticates as the GitHub App itself, and mints the short-lived
/// installation tokens which management calls are made with.
///
/// Requests made with an installation token are attributed to the App and are
/// scoped to the repositories that installation was granted, which is what
/// makes them preferable to a personal access token for writes.
#[derive(Clone)]
pub struct GitHubAppClient {
    app_id: String,
    key: Arc<EncodingKey>,
    algorithm: Algorithm,
    api_url: String,
    http_client: reqwest::Client,
}

impl GitHubAppClient {
    pub fn new(
        config: &GitHubAppConfig,
        http_client: reqwest::Client,
    ) -> Result<Self, human_errors::Error> {
        let key = EncodingKey::from_rsa_pem(config.private_key.as_bytes()).wrap_user_err(
            "The configured GitHub App private key could not be read.",
            &[
                "Ensure that connections.github.app.private_key holds the full PEM file generated by GitHub, including its BEGIN and END lines.",
                "If you are passing it through an environment variable, make sure its newlines survived.",
            ],
        )?;

        Ok(Self {
            app_id: config.app_id.clone(),
            key: Arc::new(key),
            algorithm: Algorithm::RS256,
            api_url: GITHUB_API_URL.to_string(),
            http_client,
        })
    }

    /// Builds a client signing with a symmetric key, so that tests can exercise
    /// the HTTP paths without shipping an RSA private key in the repository.
    #[cfg(test)]
    pub fn new_for_test(
        app_id: &str,
        api_url: impl Into<String>,
        http_client: reqwest::Client,
    ) -> Self {
        Self {
            app_id: app_id.to_string(),
            key: Arc::new(EncodingKey::from_secret(b"test-key")),
            algorithm: Algorithm::HS256,
            api_url: api_url.into(),
            http_client,
        }
    }

    fn claims(&self, now: chrono::DateTime<Utc>) -> AppClaims {
        AppClaims {
            iat: (now - chrono::Duration::seconds(JWT_SKEW_SECONDS)).timestamp(),
            exp: (now + chrono::Duration::seconds(JWT_TTL_SECONDS)).timestamp(),
            iss: self.app_id.clone(),
        }
    }

    fn jwt(&self) -> Result<String, human_errors::Error> {
        jsonwebtoken::encode(
            &Header::new(self.algorithm),
            &self.claims(Utc::now()),
            &self.key,
        )
        .wrap_system_err(
            "Failed to sign a JSON Web Token for the GitHub App.",
            &["Please report this issue to the dev team on GitHub."],
        )
    }

    /// Mints (or reuses) an installation access token for the given
    /// installation.
    #[instrument(
        "services.github_app.installation_token",
        skip(self, services),
        err(Display)
    )]
    pub async fn installation_token(
        &self,
        installation_id: u64,
        services: &(impl Services + Send + Sync + 'static),
    ) -> Result<String, human_errors::Error> {
        let jwt = self.jwt()?;
        let http_client = self.http_client.clone();
        let url = format!(
            "{}/app/installations/{installation_id}/access_tokens",
            self.api_url
        );

        services
            .cache()
            .cached(
                TOKEN_CACHE_PARTITION,
                installation_id.to_string(),
                move || {
                    Box::pin(async move {
                        let response = http_client
                            .post(&url)
                            .bearer_auth(&jwt)
                            .header("Accept", "application/vnd.github+json")
                            .header("X-GitHub-Api-Version", "2022-11-28")
                            .send()
                            .await
                            .wrap_user_err(
                                "We were unable to mint a GitHub App installation token.",
                                &[
                                    "Make sure that your network connection is working properly.",
                                    "Check https://www.githubstatus.com/ for any ongoing issues with GitHub's services.",
                                ],
                            )?;

                        match response.status() {
                            reqwest::StatusCode::CREATED | reqwest::StatusCode::OK => {}
                            reqwest::StatusCode::UNAUTHORIZED => {
                                return Err(human_errors::user(
                                    "GitHub rejected the App's credentials when minting an installation token.",
                                    &[
                                        "Ensure that connections.github.app.app_id matches the App the private key belongs to.",
                                        "Check that the system clock on this host is accurate, since App JWTs are short-lived.",
                                    ],
                                ));
                            }
                            reqwest::StatusCode::NOT_FOUND => {
                                return Err(human_errors::user(
                                    format!("GitHub App installation '{installation_id}' no longer exists."),
                                    &["The App may have been uninstalled from that account; reinstall it to continue."],
                                ));
                            }
                            status => {
                                return Err(human_errors::user(
                                    format!("Failed to mint a GitHub App installation token (status {status})."),
                                    &[
                                        "Make sure that your network connection is working properly.",
                                        "Check https://www.githubstatus.com/ for any ongoing issues with GitHub's services.",
                                    ],
                                ));
                            }
                        }

                        let token: InstallationTokenResponse = response.json().await.wrap_system_err(
                            "Failed to read GitHub's installation token response.",
                            &["Please report this issue to the dev team on GitHub so the model can be updated."],
                        )?;

                        Ok(token.token)
                    })
                },
                chrono::Duration::minutes(TOKEN_CACHE_MINUTES),
            )
            .await
    }

    /// Lists every account the App is currently installed on.
    #[instrument("services.github_app.installations", skip(self), err(Display))]
    pub async fn installations(&self) -> Result<Vec<GitHubInstallation>, human_errors::Error> {
        let response = self
            .http_client
            .get(format!("{}/app/installations", self.api_url))
            .bearer_auth(self.jwt()?)
            .header("Accept", "application/vnd.github+json")
            .header("X-GitHub-Api-Version", "2022-11-28")
            .send()
            .await
            .wrap_user_err(
                "We were unable to list the GitHub App's installations.",
                &[
                    "Make sure that your network connection is working properly.",
                    "Check https://www.githubstatus.com/ for any ongoing issues with GitHub's services.",
                ],
            )?;

        if !response.status().is_success() {
            return Err(human_errors::user(
                format!(
                    "Failed to list GitHub App installations (status {}).",
                    response.status()
                ),
                &[
                    "Ensure that connections.github.app.app_id matches the App the private key belongs to.",
                    "Check that the system clock on this host is accurate, since App JWTs are short-lived.",
                ],
            ));
        }

        let installations: Vec<InstallationResponse> = response.json().await.wrap_system_err(
            "Failed to read GitHub's installations response.",
            &["Please report this issue to the dev team on GitHub so the model can be updated."],
        )?;

        Ok(installations
            .into_iter()
            .map(|i| GitHubInstallation {
                id: i.id,
                account: i.account.login,
                account_type: i.account.type_,
            })
            .collect())
    }
}

#[derive(Serialize, Deserialize)]
struct AppClaims {
    iat: i64,
    exp: i64,
    iss: String,
}

#[derive(Deserialize)]
struct InstallationTokenResponse {
    token: String,
}

#[derive(Deserialize)]
struct InstallationResponse {
    id: u64,
    account: InstallationAccount,
}

#[derive(Deserialize)]
struct InstallationAccount {
    login: String,
    #[serde(rename = "type", default)]
    type_: String,
}

#[cfg(test)]
mod tests {
    use super::*;
    use wiremock::matchers::{method, path};
    use wiremock::{Mock, MockServer, ResponseTemplate};

    #[test]
    fn claims_stay_inside_githubs_ten_minute_window() {
        let client =
            GitHubAppClient::new_for_test("123", "https://example.com", reqwest::Client::new());
        let now = Utc::now();
        let claims = client.claims(now);

        assert_eq!(claims.iss, "123");
        assert!(
            claims.iat < now.timestamp(),
            "iat is backdated for clock skew"
        );
        assert!(
            claims.exp - now.timestamp() < 600,
            "GitHub rejects JWTs expiring more than ten minutes out"
        );
        assert!(claims.exp > now.timestamp());
    }

    #[tokio::test]
    async fn installation_tokens_are_minted_once_and_reused() {
        let server = MockServer::start().await;
        let services = crate::testing::mock_services()
            .await
            .expect("build mock services");

        Mock::given(method("POST"))
            .and(path("/app/installations/42/access_tokens"))
            .respond_with(ResponseTemplate::new(201).set_body_json(serde_json::json!({
                "token": "ghs_installationtoken",
                "expires_at": "2026-08-02T12:00:00Z",
            })))
            .expect(1)
            .mount(&server)
            .await;

        let client = GitHubAppClient::new_for_test("123", server.uri(), services.http_client());

        for _ in 0..3 {
            assert_eq!(
                client
                    .installation_token(42, &services)
                    .await
                    .expect("the token should be minted"),
                "ghs_installationtoken"
            );
        }
    }

    #[tokio::test]
    async fn a_removed_installation_is_reported_clearly() {
        let server = MockServer::start().await;
        let services = crate::testing::mock_services()
            .await
            .expect("build mock services");

        Mock::given(method("POST"))
            .and(path("/app/installations/42/access_tokens"))
            .respond_with(ResponseTemplate::new(404))
            .mount(&server)
            .await;

        let client = GitHubAppClient::new_for_test("123", server.uri(), services.http_client());
        let err = client
            .installation_token(42, &services)
            .await
            .expect_err("a missing installation should be an error");

        assert!(err.to_string().contains("no longer exists"));
    }

    #[tokio::test]
    async fn installations_are_flattened_onto_their_accounts() {
        let server = MockServer::start().await;
        let services = crate::testing::mock_services()
            .await
            .expect("build mock services");

        Mock::given(method("GET"))
            .and(path("/app/installations"))
            .respond_with(ResponseTemplate::new(200).set_body_json(serde_json::json!([
                { "id": 1, "account": { "login": "notheotherben", "type": "User" } },
                { "id": 2, "account": { "login": "SierraSoftworks", "type": "Organization" } },
            ])))
            .mount(&server)
            .await;

        let client = GitHubAppClient::new_for_test("123", server.uri(), services.http_client());

        assert_eq!(
            client.installations().await.expect("list installations"),
            vec![
                GitHubInstallation {
                    id: 1,
                    account: "notheotherben".to_string(),
                    account_type: "User".to_string(),
                },
                GitHubInstallation {
                    id: 2,
                    account: "SierraSoftworks".to_string(),
                    account_type: "Organization".to_string(),
                },
            ]
        );
    }
}
