use std::sync::Arc;

use chrono::Utc;
use jsonwebtoken::{Algorithm, EncodingKey, Header};

use crate::config::GitHubAppConfig;
use crate::prelude::*;

/// The API a GitHub App's management calls go to unless the operator names
/// another one, which only a GitHub Enterprise Server instance would.
const GITHUB_API_URL: &str = "https://api.github.com";

/// Installation tokens live for an hour. Caching them for slightly less leaves
/// enough margin that a long-running job cannot be caught out mid-flight.
const TOKEN_CACHE_MINUTES: i64 = 50;

/// GitHub rejects app JWTs whose expiry is more than ten minutes away, and
/// backdates `iat` slightly to tolerate clock skew between us and GitHub.
const JWT_TTL_SECONDS: i64 = 9 * 60;
const JWT_SKEW_SECONDS: i64 = 60;

/// The only algorithm GitHub accepts for an App JWT, which is why the key is
/// always an RSA one.
const APP_JWT_ALGORITHM: Algorithm = Algorithm::RS256;

const TOKEN_CACHE_PARTITION: &str = "github/installation-token";

/// GitHub's maximum page size for the installations listing.
const INSTALLATIONS_PER_PAGE: usize = 100;

/// A backstop so a misbehaving API cannot spin the listing forever. At 100 per
/// page this is far beyond any plausible number of installations for a single
/// Automate instance.
const MAX_INSTALLATION_PAGES: usize = 20;

/// An account which has installed the GitHub App.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct GitHubInstallation {
    pub id: u64,
    /// The user or organization the App is installed on.
    pub account: String,
    /// `User` or `Organization`.
    pub account_type: String,
}

/// Authenticates as the GitHub App itself, and mints the short-lived
/// installation tokens which management calls are made with.
///
/// Requests made with an installation token are attributed to the App and are
/// scoped to the repositories that installation was granted, which is what
/// makes them preferable to a personal access token for writes.
#[derive(Clone)]
pub struct GitHubAppClient {
    app_id: String,
    key: Arc<EncodingKey>,
    api_url: String,
    http_client: reqwest::Client,
}

impl GitHubAppClient {
    pub fn new(
        config: &GitHubAppConfig,
        http_client: reqwest::Client,
    ) -> Result<Self, human_errors::Error> {
        let key = EncodingKey::from_rsa_pem(config.private_key.as_bytes()).wrap_user_err(
            "The configured GitHub App private key could not be read.",
            &[
                "Ensure that connections.github.app.private_key holds the full PEM file generated by GitHub, including its BEGIN and END lines.",
                "If you are passing it through an environment variable, make sure its newlines survived.",
            ],
        )?;

        Ok(Self {
            app_id: config.app_id.clone(),
            key: Arc::new(key),
            api_url: config
                .api_url
                .clone()
                .unwrap_or_else(|| GITHUB_API_URL.to_string()),
            http_client,
        })
    }

    fn claims(&self, now: chrono::DateTime<Utc>) -> AppClaims {
        AppClaims {
            iat: (now - chrono::Duration::seconds(JWT_SKEW_SECONDS)).timestamp(),
            exp: (now + chrono::Duration::seconds(JWT_TTL_SECONDS)).timestamp(),
            iss: self.app_id.clone(),
        }
    }

    fn jwt(&self) -> Result<String, human_errors::Error> {
        jsonwebtoken::encode(
            &Header::new(APP_JWT_ALGORITHM),
            &self.claims(Utc::now()),
            &self.key,
        )
        .wrap_system_err(
            "Failed to sign a JSON Web Token for the GitHub App.",
            &["Please report this issue to the dev team on GitHub."],
        )
    }

    /// Mints (or reuses) an installation access token for the given
    /// installation.
    #[instrument(
        "services.github_app.installation_token",
        skip(self, services),
        err(Display)
    )]
    pub async fn installation_token(
        &self,
        installation_id: u64,
        services: &(impl Services + Send + Sync + 'static),
    ) -> Result<String, human_errors::Error> {
        let jwt = self.jwt()?;
        let http_client = self.http_client.clone();
        let url = format!(
            "{}/app/installations/{installation_id}/access_tokens",
            self.api_url
        );

        services
            .cache()
            .cached(
                TOKEN_CACHE_PARTITION,
                installation_id.to_string(),
                move || {
                    Box::pin(async move {
                        let response = http_client
                            .post(&url)
                            .bearer_auth(&jwt)
                            .header("Accept", "application/vnd.github+json")
                            .header("X-GitHub-Api-Version", "2022-11-28")
                            .send()
                            .await
                            .wrap_user_err(
                                "We were unable to mint a GitHub App installation token.",
                                &[
                                    "Make sure that your network connection is working properly.",
                                    "Check https://www.githubstatus.com/ for any ongoing issues with GitHub's services.",
                                ],
                            )?;

                        match response.status() {
                            reqwest::StatusCode::CREATED | reqwest::StatusCode::OK => {}
                            reqwest::StatusCode::UNAUTHORIZED => {
                                return Err(human_errors::user(
                                    "GitHub rejected the App's credentials when minting an installation token.",
                                    &[
                                        "Ensure that connections.github.app.app_id matches the App the private key belongs to.",
                                        "Check that the system clock on this host is accurate, since App JWTs are short-lived.",
                                    ],
                                ));
                            }
                            reqwest::StatusCode::NOT_FOUND => {
                                return Err(human_errors::user(
                                    format!("GitHub App installation '{installation_id}' no longer exists."),
                                    &["The App may have been uninstalled from that account; reinstall it to continue."],
                                ));
                            }
                            status => {
                                return Err(human_errors::user(
                                    format!("Failed to mint a GitHub App installation token (status {status})."),
                                    &[
                                        "Make sure that your network connection is working properly.",
                                        "Check https://www.githubstatus.com/ for any ongoing issues with GitHub's services.",
                                    ],
                                ));
                            }
                        }

                        let token: InstallationTokenResponse = response.json().await.wrap_system_err(
                            "Failed to read GitHub's installation token response.",
                            &["Please report this issue to the dev team on GitHub so the model can be updated."],
                        )?;

                        Ok(token.token)
                    })
                },
                chrono::Duration::minutes(TOKEN_CACHE_MINUTES),
            )
            .await
    }

    /// Lists every account the App is currently installed on.
    ///
    /// Paginated, because both the install wizard and the connections listing
    /// need the *complete* set: the wizard confirms a just-created installation
    /// against it, and would reject a legitimate install that happened to fall
    /// beyond the first page.
    #[instrument("services.github_app.installations", skip(self), err(Display))]
    pub async fn installations(&self) -> Result<Vec<GitHubInstallation>, human_errors::Error> {
        let mut installations = Vec::new();

        for page in 1..=MAX_INSTALLATION_PAGES {
            let response = self
                .http_client
                .get(format!("{}/app/installations", self.api_url))
                .query(&[
                    ("per_page", INSTALLATIONS_PER_PAGE.to_string()),
                    ("page", page.to_string()),
                ])
                .bearer_auth(self.jwt()?)
                .header("Accept", "application/vnd.github+json")
                .header("X-GitHub-Api-Version", "2022-11-28")
                .send()
                .await
                .wrap_user_err(
                    "We were unable to list the GitHub App's installations.",
                    &[
                        "Make sure that your network connection is working properly.",
                        "Check https://www.githubstatus.com/ for any ongoing issues with GitHub's services.",
                    ],
                )?;

            if !response.status().is_success() {
                return Err(human_errors::user(
                    format!(
                        "Failed to list GitHub App installations (status {}).",
                        response.status()
                    ),
                    &[
                        "Ensure that connections.github.app.app_id matches the App the private key belongs to.",
                        "Check that the system clock on this host is accurate, since App JWTs are short-lived.",
                    ],
                ));
            }

            let batch: Vec<InstallationResponse> = response.json().await.wrap_system_err(
                "Failed to read GitHub's installations response.",
                &["Please report this issue to the dev team on GitHub so the model can be updated."],
            )?;

            let exhausted = batch.len() < INSTALLATIONS_PER_PAGE;

            installations.extend(batch.into_iter().map(|i| GitHubInstallation {
                id: i.id,
                account: i.account.login,
                account_type: i.account.type_,
            }));

            if exhausted {
                return Ok(installations);
            }
        }

        // Far beyond any plausible number of installations for one Automate
        // instance; stopping is better than looping forever on a misbehaving API.
        warn!(
            "Stopped listing GitHub App installations after {MAX_INSTALLATION_PAGES} pages; the list may be incomplete."
        );

        Ok(installations)
    }

    /// Uninstalls the App from an account, revoking the access it was granted.
    ///
    /// An installation GitHub has already forgotten is treated as success, so
    /// that removing a stale entry twice is not an error.
    #[instrument("services.github_app.uninstall", skip(self), err(Display))]
    pub async fn uninstall(&self, installation_id: u64) -> Result<(), human_errors::Error> {
        let response = self
            .http_client
            .delete(format!(
                "{}/app/installations/{installation_id}",
                self.api_url
            ))
            .bearer_auth(self.jwt()?)
            .header("Accept", "application/vnd.github+json")
            .header("X-GitHub-Api-Version", "2022-11-28")
            .send()
            .await
            .wrap_user_err(
                "We were unable to uninstall the GitHub App.",
                &[
                    "Make sure that your network connection is working properly.",
                    "Check https://www.githubstatus.com/ for any ongoing issues with GitHub's services.",
                ],
            )?;

        if response.status() == reqwest::StatusCode::NOT_FOUND {
            debug!("GitHub App installation {installation_id} was already removed.");
            return Ok(());
        }

        if !response.status().is_success() {
            return Err(human_errors::user(
                format!(
                    "Failed to uninstall GitHub App installation {installation_id} (status {}).",
                    response.status()
                ),
                &[
                    "Ensure that connections.github.app.app_id matches the App the private key belongs to.",
                    "You can also remove the installation from the account's GitHub settings.",
                ],
            ));
        }

        Ok(())
    }
}

#[derive(Serialize, Deserialize)]
struct AppClaims {
    iat: i64,
    exp: i64,
    iss: String,
}

#[derive(Deserialize)]
struct InstallationTokenResponse {
    token: String,
}

#[derive(Deserialize)]
struct InstallationResponse {
    id: u64,
    account: InstallationAccount,
}

#[derive(Deserialize)]
struct InstallationAccount {
    login: String,
    #[serde(rename = "type", default)]
    type_: String,
}

#[cfg(test)]
mod tests {
    use super::*;
    use wiremock::matchers::{method, path, query_param};
    use wiremock::{Mock, MockServer, ResponseTemplate};

    /// A client for an App whose calls land on the mock server.
    ///
    /// Built through [`GitHubAppClient::new`], from a configuration, which is
    /// the constructor the running agent uses: the only thing a test arranges
    /// is where the calls go, and that is a thing an operator can arrange too.
    fn client(server: &MockServer, services: &impl Services) -> GitHubAppClient {
        GitHubAppClient::new(
            &crate::testing::github_app(server.uri()),
            services.http_client(),
        )
        .expect("build a client for the App under test")
    }

    #[test]
    fn claims_stay_inside_githubs_ten_minute_window() {
        let client = GitHubAppClient::new(
            &crate::testing::github_app("https://example.com"),
            reqwest::Client::new(),
        )
        .expect("build a client for the App under test");
        let now = Utc::now();
        let claims = client.claims(now);

        assert_eq!(claims.iss, "123");
        assert!(
            claims.iat < now.timestamp(),
            "iat is backdated for clock skew"
        );
        assert!(
            claims.exp - now.timestamp() < 600,
            "GitHub rejects JWTs expiring more than ten minutes out"
        );
        assert!(claims.exp > now.timestamp());
    }

    /// Almost every instance is on github.com and says nothing about an API
    /// URL, so leaving it out has to mean github.com rather than nowhere.
    #[test]
    fn an_app_that_names_no_api_talks_to_github_com() {
        let config = GitHubAppConfig {
            api_url: None,
            ..crate::testing::github_app("https://ghe.example.com/api/v3")
        };

        let client = GitHubAppClient::new(&config, reqwest::Client::new())
            .expect("build a client for the App under test");

        assert_eq!(client.api_url, GITHUB_API_URL);
    }

    #[tokio::test]
    async fn installation_tokens_are_minted_once_and_reused() {
        let server = MockServer::start().await;
        let services = crate::testing::mock_services()
            .await
            .expect("build mock services");

        Mock::given(method("POST"))
            .and(path("/app/installations/42/access_tokens"))
            .respond_with(ResponseTemplate::new(201).set_body_json(serde_json::json!({
                "token": "ghs_installationtoken",
                "expires_at": "2026-08-02T12:00:00Z",
            })))
            .expect(1)
            .mount(&server)
            .await;

        let client = client(&server, &services);

        for _ in 0..3 {
            assert_eq!(
                client
                    .installation_token(42, &services)
                    .await
                    .expect("the token should be minted"),
                "ghs_installationtoken"
            );
        }
    }

    #[tokio::test]
    async fn a_removed_installation_is_reported_clearly() {
        let server = MockServer::start().await;
        let services = crate::testing::mock_services()
            .await
            .expect("build mock services");

        Mock::given(method("POST"))
            .and(path("/app/installations/42/access_tokens"))
            .respond_with(ResponseTemplate::new(404))
            .mount(&server)
            .await;

        let client = client(&server, &services);
        let err = client
            .installation_token(42, &services)
            .await
            .expect_err("a missing installation should be an error");

        assert!(err.to_string().contains("no longer exists"));
    }

    #[tokio::test]
    async fn installations_are_flattened_onto_their_accounts() {
        let server = MockServer::start().await;
        let services = crate::testing::mock_services()
            .await
            .expect("build mock services");

        Mock::given(method("GET"))
            .and(path("/app/installations"))
            .respond_with(ResponseTemplate::new(200).set_body_json(serde_json::json!([
                { "id": 1, "account": { "login": "notheotherben", "type": "User" } },
                { "id": 2, "account": { "login": "SierraSoftworks", "type": "Organization" } },
            ])))
            .mount(&server)
            .await;

        let client = client(&server, &services);

        assert_eq!(
            client.installations().await.expect("list installations"),
            vec![
                GitHubInstallation {
                    id: 1,
                    account: "notheotherben".to_string(),
                    account_type: "User".to_string(),
                },
                GitHubInstallation {
                    id: 2,
                    account: "SierraSoftworks".to_string(),
                    account_type: "Organization".to_string(),
                },
            ]
        );
    }

    /// A full page means there may be more. The install wizard confirms a
    /// just-created installation against this list, so stopping at the first page
    /// would reject a legitimate install on a busy App.
    #[tokio::test]
    async fn installations_beyond_the_first_page_are_collected() {
        let server = MockServer::start().await;
        let services = crate::testing::mock_services()
            .await
            .expect("build mock services");

        let first_page: Vec<serde_json::Value> = (1..=INSTALLATIONS_PER_PAGE)
            .map(|i| {
                serde_json::json!({ "id": i, "account": { "login": format!("acct{i}"), "type": "User" } })
            })
            .collect();

        Mock::given(method("GET"))
            .and(path("/app/installations"))
            .and(query_param("page", "1"))
            .respond_with(ResponseTemplate::new(200).set_body_json(first_page))
            .mount(&server)
            .await;

        Mock::given(method("GET"))
            .and(path("/app/installations"))
            .and(query_param("page", "2"))
            .respond_with(ResponseTemplate::new(200).set_body_json(serde_json::json!([
                { "id": 999, "account": { "login": "last", "type": "Organization" } },
            ])))
            .mount(&server)
            .await;

        let client = client(&server, &services);
        let installations = client.installations().await.expect("list installations");

        assert_eq!(installations.len(), INSTALLATIONS_PER_PAGE + 1);
        assert_eq!(installations.last().unwrap().account, "last");
    }

    /// A short page means the listing is exhausted, so we must not ask for
    /// another one.
    #[tokio::test]
    async fn a_short_page_ends_the_listing() {
        let server = MockServer::start().await;
        let services = crate::testing::mock_services()
            .await
            .expect("build mock services");

        Mock::given(method("GET"))
            .and(path("/app/installations"))
            .respond_with(ResponseTemplate::new(200).set_body_json(serde_json::json!([
                { "id": 1, "account": { "login": "only", "type": "User" } },
            ])))
            .expect(1)
            .mount(&server)
            .await;

        let client = client(&server, &services);
        assert_eq!(client.installations().await.unwrap().len(), 1);
    }

    #[tokio::test]
    async fn uninstalling_revokes_the_installation() {
        let server = MockServer::start().await;
        let services = crate::testing::mock_services()
            .await
            .expect("build mock services");

        Mock::given(method("DELETE"))
            .and(path("/app/installations/42"))
            .respond_with(ResponseTemplate::new(204))
            .expect(1)
            .mount(&server)
            .await;

        let client = client(&server, &services);
        client.uninstall(42).await.expect("uninstall");
    }

    /// Removing a stale entry is exactly when an installation is already gone, so
    /// a 404 has to be success rather than an error the operator cannot resolve.
    #[tokio::test]
    async fn uninstalling_something_already_gone_succeeds() {
        let server = MockServer::start().await;
        let services = crate::testing::mock_services()
            .await
            .expect("build mock services");

        Mock::given(method("DELETE"))
            .and(path("/app/installations/42"))
            .respond_with(ResponseTemplate::new(404))
            .mount(&server)
            .await;

        let client = client(&server, &services);
        client
            .uninstall(42)
            .await
            .expect("a missing installation is not an error");
    }

    #[tokio::test]
    async fn a_refused_uninstall_is_reported() {
        let server = MockServer::start().await;
        let services = crate::testing::mock_services()
            .await
            .expect("build mock services");

        Mock::given(method("DELETE"))
            .and(path("/app/installations/42"))
            .respond_with(ResponseTemplate::new(403))
            .mount(&server)
            .await;

        let client = client(&server, &services);
        let err = client
            .uninstall(42)
            .await
            .expect_err("a 403 should surface");
        assert!(err.to_string().contains("403"));
    }
}
